// analyze_schema.go - JSON Schema export for --auto Findings NDJSON.
//
// Emitted via the --auto-print-schema flag. The schema is a constant string
// embedded in the Go binary so consumers can validate Finding streams in CI
// pipelines, get autocomplete in IDEs, etc. Schema is Draft 2020-12.
//
// The schema describes the UNION of all Finding kinds. Each line of the
// --auto NDJSON stream is one Finding object that must validate against the
// schema. JSON Schema's discriminator-style union (`oneOf` keyed on `kind`)
// is the natural fit.
package main

// jsonSchemaText returns the JSON Schema as a string. Single source of
// truth for the contract between the parser and the analyzer skill /
// downstream consumers.
func jsonSchemaText() string {
	return autoFindingsJSONSchema
}

// autoFindingsJSONSchema is the literal Draft 2020-12 schema. Updates to
// Finding kinds or fields must be reflected here AND bump SchemaVersion
// when the change is breaking.
const autoFindingsJSONSchema = `{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://mongodb.internal/ftdc-parser/auto-findings.schema.json",
  "title": "FTDC --auto Findings",
  "description": "Schema for the NDJSON stream emitted by ftdc_parser --auto. Each line is one Finding object.",
  "type": "object",
  "required": ["schema_version", "kind", "id"],
  "properties": {
    "schema_version": {"type": "string", "const": "1"},
    "kind": {
      "type": "string",
      "enum": [
        "run_metadata",
        "schema_fingerprint",
        "metric_score_table",
        "mover",
        "correlation",
        "monotonic_trend",
        "changepoint",
        "changepoint_oversegmented",
        "metric_context",
        "metric_glossary",
        "truncated",
        "capacity_pressure",
        "near_ceiling",
        "consistency_warning",
        "synthetic_event",
        "periodic",
        "suspicious_smoothness",
        "evidence_convergence",
        "utilization",
        "alert_threshold",
        "clock_skew",
        "missing_signal",
        "term_change",
        "replication_buffer_pressure",
        "oplog_window_low",
        "checkpoint_install_anomaly",
        "materialization_lag",
        "io_routing",
        "chunk_migration_event",
        "balancer_round_stall",
        "host_pathology",
        "workload_spec",
        "precursor_candidates",
        "memory_triplet",
        "recurrence_fingerprint",
        "histogram_percentile",
        "histogram_invalid",
        "gap",
        "variance_shift",
        "spike",
        "skipped",
        "host_only_metrics",
        "cross_host_drift",
        "cross_host_role_inferred",
        "host_metric_set_asymmetry",
        "trend_inconclusive",
        "counter_wrap",
        "counter_inversion",
        "local_spike",
        "glossary_gap",
        "regression",
        "baseline_diagnostic",
        "apply_saturation",
        "election_storm",
        "checkpoint_stall",
        "eviction_divergence",
        "capture_quality_score",
        "chunk_decode_error",
        "diagnosis_candidate",
        "hypothesis_test",
        "seal_event",
        "seal_event_candidate",
        "role_asymmetry",
        "node_pair_asymmetry",
        "window_suggestion",
        "diagnosis_uncertainty",
        "joint_changepoint",
        "quantile_trend",
        "mover_stratified",
        "coverage_summary",
        "coverage_gap",
        "followups_backlog_snapshot",
        "recap",
        "stored_inference_review",
        "similar_prior_capture",
        "capture_diff",
        "capture_diff_summary",
        "tunable_observation",
        "tunable_counterfactual",
        "tunable_counterfactual_refused",
        "converge_plan",
        "convergence_failed",
        "sweep_discriminator",
        "sweep_label_audit",
        "sweep_inconclusive",
        "run_health"
      ]
    },
    "id": {"type": "string", "pattern": "^f-[0-9a-f]{8}$"},
    "host": {"type": "string"}
  },
  "oneOf": [
    {"properties": {"kind": {"const": "run_metadata"}}},
    {"properties": {"kind": {"const": "schema_fingerprint"}}, "required": ["fingerprint", "metric_count"]},
    {"properties": {"kind": {"const": "metric_score_table"}}, "required": ["entries"]},
    {"properties": {"kind": {"const": "mover"}}, "required": ["metric", "metric_kind", "direction", "score", "welch_t", "baseline", "stress"]},
    {"properties": {"kind": {"const": "correlation"}}, "required": ["leader", "follower", "lag_seconds", "pearson"]},
    {"properties": {"kind": {"const": "monotonic_trend"}}, "required": ["metric", "spearman", "slope", "slope_t"]},
    {"properties": {"kind": {"const": "changepoint"}}, "required": ["metric", "at", "sample_index", "effect_size", "confidence_rank", "cross_validated"]},
    {"properties": {"kind": {"const": "changepoint_oversegmented"}}, "required": ["metric", "metric_kind", "break_count", "reason_code"]},
    {"properties": {"kind": {"const": "metric_context"}}, "required": ["host", "metric_count"]},
    {"properties": {"kind": {"const": "metric_glossary"}}, "required": ["entries", "cited_count", "covered"]},
    {"properties": {"kind": {"const": "truncated"}}, "required": ["kinds_elided", "budget_tokens"]},
    {"properties": {"kind": {"const": "capacity_pressure"}}, "required": ["metric", "ceiling_metric", "ceiling_kind", "pct_at_ceiling", "pct_near_ceiling", "longest_run_seconds"]},
    {"properties": {"kind": {"const": "near_ceiling"}}, "required": ["metric", "last_value", "ceiling_value", "last_ratio"]},
    {"properties": {"kind": {"const": "consistency_warning"}}, "required": ["metric", "reason_code"]},
    {"properties": {"kind": {"const": "synthetic_event"}}, "required": ["at_start", "at_end", "member_count", "metric_family_count", "member_finding_ids"]},
    {"properties": {"kind": {"const": "periodic"}}, "required": ["metric", "period_seconds", "snr", "threshold"]},
    {"properties": {"kind": {"const": "suspicious_smoothness"}}, "required": ["metric", "detector", "reason_code"]},
    {"properties": {"kind": {"const": "evidence_convergence"}}, "required": ["synthetic_event_id", "distinct_kinds_count", "kinds"]},
    {"properties": {"kind": {"const": "utilization"}}, "required": ["metric", "display_kind", "mean", "p50", "p95", "max"]},
    {"properties": {"kind": {"const": "alert_threshold"}}, "required": ["alert_class", "at"]},
    {"properties": {"kind": {"const": "clock_skew"}}, "required": ["host", "max_drift_ms", "reason_code"]},
    {"properties": {"kind": {"const": "missing_signal"}}, "required": ["metric", "category", "reason_code"]},
    {"properties": {"kind": {"const": "term_change"}}, "required": ["at", "prior_term", "new_term"]},
    {"properties": {"kind": {"const": "replication_buffer_pressure"}}, "required": ["metric", "denom_metric", "p95"]},
    {"properties": {"kind": {"const": "oplog_window_low"}}, "required": ["metric", "min_hours", "at"]},
    {"properties": {"kind": {"const": "checkpoint_install_anomaly"}}, "required": ["metric", "count_increase"]},
    {"properties": {"kind": {"const": "materialization_lag"}}, "required": ["metric", "p95_ms"]},
    {"properties": {"kind": {"const": "io_routing"}}, "required": ["local_success_delta", "non_local_success_delta", "local_fraction"]},
    {"properties": {"kind": {"const": "chunk_migration_event"}}, "required": ["metric", "migrations_started"]},
    {"properties": {"kind": {"const": "balancer_round_stall"}}, "required": ["metric", "failed_rounds"]},
    {"properties": {"kind": {"const": "host_pathology"}}, "required": ["subkind"]},
    {"properties": {"kind": {"const": "workload_spec"}}, "required": ["host", "sample_count"]},
    {"properties": {"kind": {"const": "precursor_candidates"}}, "required": ["target_finding_id", "target_metric", "precursors"]},
    {"properties": {"kind": {"const": "memory_triplet"}}, "required": ["host"]},
    {"properties": {"kind": {"const": "recurrence_fingerprint"}}, "required": ["host", "fingerprint", "shape"]},
    {"properties": {"kind": {"const": "histogram_percentile"}}, "required": ["metric", "window", "pattern", "ops"]},
    {"properties": {"kind": {"const": "histogram_invalid"}}, "required": ["metric", "window", "pattern", "reason"]},
    {"properties": {"kind": {"const": "gap"}}, "required": ["at", "end_at", "duration_seconds"]},
    {"properties": {"kind": {"const": "variance_shift"}}, "required": ["metric", "at", "cusum_peak"]},
    {"properties": {"kind": {"const": "spike"}}, "required": ["metric", "at", "z_score", "value", "median"]},
    {"properties": {"kind": {"const": "skipped"}}, "required": ["reason"]},
    {"properties": {"kind": {"const": "host_only_metrics"}}, "required": ["host", "metrics"]},
    {"properties": {"kind": {"const": "cross_host_drift"}}, "required": ["metric", "ratio", "hosts"]},
    {"properties": {"kind": {"const": "cross_host_role_inferred"}}, "required": ["host", "role"]},
    {"properties": {"kind": {"const": "host_metric_set_asymmetry"}}, "required": ["host", "evidence"]},
    {"properties": {"kind": {"const": "trend_inconclusive"}}, "required": ["metric", "reason_code"]},
    {"properties": {"kind": {"const": "counter_wrap"}}, "required": ["metric", "at"]},
    {"properties": {"kind": {"const": "counter_inversion"}}, "required": ["metric", "at"]},
    {"properties": {"kind": {"const": "local_spike"}}, "required": ["metric", "at", "z_score"]},
    {"properties": {"kind": {"const": "glossary_gap"}}, "required": ["uncatalogued_metrics", "uncatalogued_count"]},
    {"properties": {"kind": {"const": "regression"}}, "required": ["metric", "current_mean", "baseline_mean", "deviation_sigmas"]},
    {"properties": {"kind": {"const": "baseline_diagnostic"}}, "required": ["host_token", "baseline_rows"]},
    {"properties": {"kind": {"const": "apply_saturation"}}, "required": ["metric", "avg_ms_per_batch"]},
    {"properties": {"kind": {"const": "election_storm"}}, "required": ["window_start", "term_change_count"]},
    {"properties": {"kind": {"const": "checkpoint_stall"}}, "required": ["metric", "max_duration_ms"]},
    {"properties": {"kind": {"const": "eviction_divergence"}}, "required": ["metric", "ratio"]},
    {"properties": {"kind": {"const": "capture_quality_score"}}, "required": ["score"]},
    {"properties": {"kind": {"const": "chunk_decode_error"}}, "required": ["reason_code"]},
    {"properties": {"kind": {"const": "diagnosis_candidate"}}, "required": ["pattern_name", "supporting_finding_ids", "confidence_rank", "rationale"]},
    {"properties": {"kind": {"const": "hypothesis_test"}}, "required": ["parent_finding_id", "parent_pattern_name", "recipe"]},
    {"properties": {"kind": {"const": "run_health"}}, "required": ["findings_emitted_by_kind", "sample_count"]},
    {"properties": {"kind": {"const": "capture_diff"}}, "required": ["kind"]},
    {"properties": {"kind": {"const": "capture_diff_summary"}}, "required": ["kind"]},
    {"properties": {"kind": {"const": "converge_plan"}}, "required": ["kind"]},
    {"properties": {"kind": {"const": "convergence_failed"}}, "required": ["kind"]},
    {"properties": {"kind": {"const": "coverage_gap"}}, "required": ["kind"]},
    {"properties": {"kind": {"const": "coverage_summary"}}, "required": ["kind"]},
    {"properties": {"kind": {"const": "diagnosis_uncertainty"}}, "required": ["kind"]},
    {"properties": {"kind": {"const": "followups_backlog_snapshot"}}, "required": ["kind"]},
    {"properties": {"kind": {"const": "joint_changepoint"}}, "required": ["kind"]},
    {"properties": {"kind": {"const": "mover_stratified"}}, "required": ["kind"]},
    {"properties": {"kind": {"const": "node_pair_asymmetry"}}, "required": ["kind"]},
    {"properties": {"kind": {"const": "quantile_trend"}}, "required": ["kind"]},
    {"properties": {"kind": {"const": "recap"}}, "required": ["kind"]},
    {"properties": {"kind": {"const": "role_asymmetry"}}, "required": ["kind"]},
    {"properties": {"kind": {"const": "seal_event"}}, "required": ["kind"]},
    {"properties": {"kind": {"const": "seal_event_candidate"}}, "required": ["kind"]},
    {"properties": {"kind": {"const": "similar_prior_capture"}}, "required": ["kind"]},
    {"properties": {"kind": {"const": "stored_inference_review"}}, "required": ["kind"]},
    {"properties": {"kind": {"const": "sweep_discriminator"}}, "required": ["kind"]},
    {"properties": {"kind": {"const": "sweep_inconclusive"}}, "required": ["kind"]},
    {"properties": {"kind": {"const": "sweep_label_audit"}}, "required": ["kind"]},
    {"properties": {"kind": {"const": "tunable_counterfactual"}}, "required": ["kind"]},
    {"properties": {"kind": {"const": "tunable_counterfactual_refused"}}, "required": ["kind"]},
    {"properties": {"kind": {"const": "tunable_observation"}}, "required": ["kind"]},
    {"properties": {"kind": {"const": "window_suggestion"}}, "required": ["kind"]}
  ]
}`
