#!/usr/bin/env python3
"""Compress 17 over-cap hub descriptions under 1536 chars while preserving every spoke keyword.
Default dry-run; pass --apply to write. Replaces the frontmatter `description:` block."""
import os, re, sys
SK = os.path.expanduser("~/.claude/skills")
APPLY = "--apply" in sys.argv
CAP = 1536

DESCS = {
"da-data-engineering-platform": "Data-engineering & analytics-platform hub (da family) — tooling, pipelines, storage, modeling, governance beneath any analysis. TRIGGER: data tools/languages (Python, Polars, pandas, DuckDB, SQL, Spark, dbt); data engineering & pipelines (ELT/ETL, orchestration, Airflow/Dagster, modern data stack, lakehouse, warehouse loading); streaming analytics (Kafka, Flink, Spark Structured Streaming, windowing, exactly-once); semantic layer / headless BI (metric stores, dbt Semantic Layer, Cube); data observability (freshness/volume/schema/lineage pillars, data quality); reverse ETL / operational analytics; real-time OLAP engines (ClickHouse, Druid, Pinot, StarRocks); dimensional & analytics modeling (Kimball, star schema, SCD, data vault); data governance & catalogs (DAMA-DMBOK, DCAM, lineage); data FinOps / cost optimization; knowledge graphs & semantic analytics (RDF, ontologies). SKIP: cleaning/EDA/modeling/ML → da-analytical-methods; theory → da-1-foundations-theory; lifecycle → da-2-data-analysis-lifecycle; viz/comms → da-applied-and-communication.",
"mongodb-expert": "Primary MongoDB data-plane & engine hub — first choice for core MongoDB. 24 on-demand references. TRIGGER: CRUD/MQL query/projection/update; aggregation pipelines & deep stages ($lookup,$graphLookup,$facet,$bucket,$merge/$out,$setWindowFields,$densify/$fill); index design (compound/multikey/partial/wildcard/TTL/hashed); query optimization & explain plans, slow queries; schema design & data modeling (embed vs reference, patterns); transactions; change streams (resume tokens, pre/post images); time-series collections; geospatial 2dsphere/GeoJSON; views & materialized views; BSON types; error codes; connection strings; driver internals (CMAP, SDAM, server selection, retryable writes), drivers on k8s; WiredTiger internals (cache/eviction/checkpoint/MVCC); mongosh; database tools (mongodump/restore/import/export); multi-tenancy; sharding; replication; Compass. SKIP: Atlas platform/config → mongodb-atlas-expert; live perf/diagnostics → atlas-diagnostics-expert; backup/DR/migration/security/encryption → mongodb-operations-expert; KB lookup → mongodb-kb.",
"da-applied-and-communication": "Applied & domain analytics + communication & data ethics hub (da family). TRIGGER: data visualization (chart selection, encodings, dashboards, perception); reporting & communication (analysis-to-narrative, stakeholder handoff, exec summaries, data storytelling); data ethics & privacy (bias/fairness, differential privacy, anonymization, consent, responsible AI); product analytics (instrumentation, funnels, activation, adoption); marketing mix modeling & incrementality (adstock, media ROI); geospatial/spatial (vector/raster, spatial joins, choropleths); network/graph analytics (centrality, community detection); cohort & retention (retention curves, churn); synthetic data (GANs/copulas); text analytics & NLP (topic modeling, sentiment, embeddings); augmented/LLM-assisted analytics (NL-BI); pricing & revenue (elasticity, willingness-to-pay). SKIP: theory → da-1-foundations-theory; lifecycle → da-2-data-analysis-lifecycle; acquisition/sampling → da-3-data-acquisition-sampling; methods/ML → da-analytical-methods; pipelines/platform → da-data-engineering-platform.",
"tam-operations": "TAM operations hub — account deliverables, customer health, case & incident ops, reporting automation, Customer Dashboard support-data. TRIGGER: TAM deliverables — EBR/QBR, account review, support plan, engagement overview, JIMP, weekly update, case-analysis report; account health, churn risk, NRR, sentiment, health-scoring; MongoDB Premium Services operating model (TAM/NTSE/IR/DCE roles, S1–S4 SLAs, JIMP/Break-Glass/PIR-RCA, onboarding/offboarding, Straight-to-8, risk register, Monday.com tracking); parallel account-artifact collection; shift-handoff (SBAR), meeting-prep, operator reports (freshness, BLUF); customer file consolidation; active case tracker (Support API, case schema, severity, diagnostic catalog, LLM summarization); case/event timeline viz; incident response (SEV, IC/comms, blameless postmortems, SLO/SLI/error budgets, on-call, MTTD/MTTR); Monday.com board audit; Slack workspace/subscription audit. SKIP: vendor API client dev → integration-clients; MongoDB technical → mongodb-* hubs.",
"da-3-data-acquisition-sampling": "Data acquisition, collection & sampling hub (da family, stage 3). TRIGGER: data-source taxonomy (primary/secondary, internal/external, structured/semi/unstructured); collection methods (web scraping/crawling, robots.txt/legality, APIs & data feeds, REST/GraphQL/gRPC, pagination/rate-limit/auth, web/app analytics instrumentation, event tracking); data-collection overview; survey & sampling-frame design, response bias; sampling methods (simple random, stratified, cluster, systematic, convenience, quota, snowball); sample size/power; acquisition plumbing — API ingestion, DB extraction/CDC, streaming ingest (Kafka/Kinesis/Pub-Sub), ETL/ELT & modern data stack. SKIP: theory → da-1-foundations-theory; lifecycle → da-2-data-analysis-lifecycle; methods/ML → da-analytical-methods; pipelines/platform → da-data-engineering-platform; viz/comms → da-applied-and-communication.",
"da-1-foundations-theory": "Foundations & theory of data analysis hub (da family) — conceptual & mathematical grounding beneath any technique. TRIGGER: definitions/scope (analysis vs analytics vs data science vs statistics, quantitative vs qualitative); measurement (levels nominal/ordinal/interval/ratio, measurement theory, reliability/validity, operationalization, constructs); probability (random variables, PMF/PDF, named distributions, joint/marginal/conditional, Bayes, LLN, CLT, expectation/variance/covariance); statistical inference foundations (population vs sample, sampling distributions, standard error, frequentist vs Bayesian, estimation theory); information theory (entropy, mutual information); epistemology (correlation vs causation, inductive vs deductive, reproducibility/replicability). SKIP: lifecycle → da-2-data-analysis-lifecycle; acquisition/sampling → da-3-data-acquisition-sampling; methods/ML → da-analytical-methods; pipelines/platform → da-data-engineering-platform; viz/comms → da-applied-and-communication.",
"software-engineering-patterns": "Language-agnostic software design, architecture & engineering-practice hub. TRIGGER: API design (REST/GraphQL/gRPC, versioning); backend & microservices patterns (decomposition, bounded contexts, strangler fig); Express/Fastify/NestJS/Hono backend frameworks + selection; Python web frameworks (FastAPI/Django/Flask, ASGI/WSGI, uvicorn/gunicorn); design patterns (creational/structural/behavioral); coding standards; architecture methodology & docs (ISO 42010, ADRs, C4); code review (OWASP checklist); debugging & root-cause (5 Whys); performance profiling; SSE/streaming; job scheduling / MV3 alarms; auth-checker/web-auth; diagnostic registry; Vitest testing (vi mocks, coverage, snapshots, flaky tests, Jest→Vitest); Playwright local web-app/UI testing & automation; repo reusable-pattern scanning. SKIP: language syntax/idioms → lang-python/lang-js-ts/lang-go-and-mobile; frontend/UI/CSS → frontend-ui; vendor API clients → integration-clients.",
"technical-writing-craft": "Technical & product writing hub — software docs, specs, engineering comms. Sentence mechanics & structure (Given/New, active voice, imperative mood, nominalization/zombie nouns, heading discipline, cohesion/coherence, RFC 2119, Diátaxis, show-first); style-guide grounded (Google, Microsoft WSG, Strunk & White, Williams). TRIGGER: technical writing, API docs, README, readability, passive voice, heading structure; how-to & tutorials; KB articles; reference & explanation docs; runbooks/on-call; specs; PRDs; RFCs & design docs; user stories & acceptance criteria; meeting minutes & ADRs; changelogs & release notes; error messages; microcopy/UI writing; commit & PR messages; code/agent plans; postmortems; incident/status-page comms. SKIP: general prose/voice/editing → writing-expert; exec/business/persuasion → executive-comms; marketing/PR/newsletters → content-and-marketing-writing; career/academic/legal/policy/survey → career-and-formal-writing.",
"da-2-data-analysis-lifecycle": "Data-analysis lifecycle & process hub (da family) — the structured workflow from raw data to insight. TRIGGER: overall process/workflow/methodology of an analysis project; structuring/planning start-to-finish; phases/stages; iterate vs advance; process frameworks (CRISP-DM, KDD, SEMMA, OSEMN, TDSP); problem framing (business/research question, hypotheses, success metrics/KPIs, scoping/feasibility); iteration & experimentation loops; documentation & reproducibility (notebooks, provenance, environment capture); stakeholder communication & handoff. SKIP: theory → da-1-foundations-theory; acquisition/sampling → da-3-data-acquisition-sampling; methods/ML → da-analytical-methods; pipelines/platform → da-data-engineering-platform; viz/comms → da-applied-and-communication.",
"document-formats": "Generate/parse/edit/convert document & data-file formats in Python & Node — PDF, Word(.docx), Excel(.xlsx), PowerPoint(.pptx), CSV/TSV, advanced JSON, draw.io(.drawio). TRIGGER: PDF (pdf-lib, PDFKit, pypdf, ReportLab, WeasyPrint, HTML-to-PDF, extract text/tables, AcroForms, PAdES signatures, PDF/A·UA); Word .docx (docx-js, TOC, tracked changes, comments, find-replace); Excel .xlsx (openpyxl/pandas, formulas, charts, clean tabular data); PowerPoint .pptx (PptxGenJS/python-pptx, masters/layouts, charts, pptx→PDF); CSV/TSV (parse/stream/validate, encoding/BOM, formula-injection CWE-1236, csvkit/qsv/miller/DuckDB); advanced JSON (streaming, JSON Schema/Ajv/Zod, JSON Patch RFC 6902, JSONPath, MessagePack/CBOR, NDJSON, JSON5); draw.io (mxGraph XML, drawpyo, export SVG/PNG/PDF). Also a report/invoice/memo/deck/spreadsheet/diagram requested as a file. SKIP: analytical/ETL processing of tabular data → da-analytical-methods / da-data-engineering-platform; extracting FROM aging/live-DOM sources → content-ingestion-extraction.",
"content-ingestion-extraction": "Acquire, extract, audit & restructure content from heterogeneous sources — aging docs, doc folders/KBs, live web DOM, meeting-audio devices, one-off docs to templatize. TRIGGER: doc archaeology (staleness, dead links, process drift, deprecate/archive decisions); doc-store bootstrapping (numbered taxonomy, _meta indexes, archive policy); Chrome content-script DOM extractor (selector fallback, MutationObserver/waitForElement, shadow-DOM, SPA nav, partial extraction); Granola transcript/notes fetch (REST, native-host, ProseMirror, polling sync); Plaud recorder ecosystem (devices, Developer API/OAuth, MCP, AutoFlow); reverse-engineer a doc into a reconstruction prompt with {{placeholders}} + data-manifest. SKIP: producing/parsing a finished file FORMAT → document-formats; general Chrome-extension architecture → chrome-extension-expert; prose/voice → writing-expert.",
"chrome-extension-expert": "Chrome extension / MV3 development hub — build, package, secure, test browser extensions. 17 references. TRIGGER: MV3 service-worker lifecycle/idle termination; manifest.json fields, permissions, CRX packaging, Web Store publishing; chrome.runtime/chrome.tabs cross-context messaging; native messaging hosts (Python/Node, 4-byte framing); chrome.identity getAuthToken/launchWebAuthFlow OAuth; chrome.storage local/session/sync; chrome.tabs query/update/create; chrome.notifications; offscreen documents & keepalive; chrome.action badge/icon; content scripts & shadow-DOM overlays; WebSocket/Socket.IO in a service worker; Playwright E2E for unpacked extensions; marked.js + DOMPurify markdown rendering; extension security/permission/CSP review. SKIP: general frontend/UI/CSS → frontend-ui; JS/TS language → lang-js-ts; language-agnostic patterns → software-engineering-patterns.",
"integration-clients": "Third-party SaaS API & integration-client hub — Jira, Monday.com, Slack, Salesforce, Glean, Aha!. REST/GraphQL surfaces, auth (OAuth 2.0, cookie/session, API tokens), webhooks/events, SDKs/CLIs, app frameworks, calling from Chrome MV3. TRIGGER: client against a third-party SaaS API; Jira dev (REST v3, issues/search/workflows, agile) incl. from a Chrome extension; Monday.com GraphQL v2 + Monday apps (Apps Framework, mapps CLI); Slack apps (Web API, Events API, Socket Mode, Block Kit); Salesforce (REST/SOAP/Bulk 2.0/Composite/Tooling/Pub-Sub/GraphQL); Glean (CLI, MCP, SDK clients); Aha! API/webhooks. SKIP: vendor-neutral API DESIGN patterns → software-engineering-patterns; AI/LLM tool-calling → ai-mcp-sdk-prompting; generic Chrome OAuth plumbing → chrome-extension-expert; TAM ops audits (Monday board / Slack subscription) → tam-operations.",
"mongodb-operations-expert": "MongoDB/Atlas operations hub — reliability & data movement. 16 references. TRIGGER: backup/restore & point-in-time recovery; disaster recovery & RTO/RPO; Ops Manager/Cloud Manager; major-version upgrade paths & FCV; migration patterns incl. safe schema/data migrations (expand-contract, backfill, online schema change, rollback); mongosync live migration / cluster-to-cluster; Relational Migrator (RDBMS→MongoDB); CDC pipeline architecture; change streams/TTL/archival & lifecycle; security architecture, auth, network hardening; encryption at-rest/in-transit/CSFLE/Queryable Encryption; compliance & regulatory posture; Atlas cost optimization & right-sizing; Kafka connector; Spark connector/Databricks. SKIP: data-plane query/index/schema/engine → mongodb-expert; Atlas platform/features → mongodb-atlas-expert; live diagnostics/perf → atlas-diagnostics-expert; KB lookup → mongodb-kb.",
"executive-comms": "Executive & business communication hub — leadership, persuasion, decision-driving artifacts for C-suite, board, VP, investor, funder audiences. Covers BLUF, board memos, ICP briefs, status reports, decision-readiness. TRIGGER: board memo; exec summary; VP status update; make-this-exec-ready; 30-second pitch; ICP brief; decision memo; one-pager; OKRs; proposals & grants; pitch/investor decks; negotiation & persuasion prep; public speaking/presentations; keynote/conference talk; all-hands/speech writing; founder & shareholder letters; whitepapers; customer case studies. SKIP: general prose/voice/editing → writing-expert; software/product/eng docs → technical-writing-craft; marketing/PR/launch/newsletters → content-and-marketing-writing; career/academic/legal/policy/survey → career-and-formal-writing; analysis to build first → da-applied-and-communication.",
"mongodb-atlas-expert": "Broad MongoDB Atlas platform hub — control plane (orgs/projects/deployments), Admin API v2, Atlas CLI, Terraform, Kubernetes Operator (AKO), tiers (Free/Flex/Dedicated), security (IP access list, private networking, db vs Atlas users), alerts/metrics/limits, 2025-2026 refresh. 27 references. TRIGGER: Atlas architecture & surface choice (UI/Admin API/CLI/Terraform/AKO); tier/version/limit; security/networking design; alert/metric posture; and deep sub-areas — Atlas Search/$search, Vector Search/$vectorSearch, Stream Processing, Charts, Data Federation, App Services, Triggers/Functions, Device SDK/Realm sync, Online Archive, Flex/Serverless, Global Clusters, Search Nodes, Service Accounts, IAM/RBAC, Federated Auth (SAML/SSO), Azure/GCP/AWS networking & PrivateLink, BI Connector, analytics nodes. SKIP: data-plane query/index/schema/engine → mongodb-expert; live diagnostics/perf → atlas-diagnostics-expert; backup/DR/migration/security/encryption/connectors/cost → mongodb-operations-expert; KB lookup → mongodb-kb.",
"writing-expert": "General prose craft, voice, style & editing hub. Sentence/paragraph craft; writing frameworks (BLUF, Minto Pyramid, SCQA, STAR, Inverted Pyramid, 5W1H); tone/voice by audience; anti-AI-ism; data storytelling; 18 prose sub-skills on demand. TRIGGER: write/draft/edit/improve/structure/review general prose; editing & revision; rhetorical/argument frameworks; storytelling & narrative; headlines; plain & inclusive language; localization-friendly writing; anti-jargon; brand voice; audience modeling; visual writing (captions, alt text, chart copy); accessibility writing; AI-collaboration writing; writing under pressure; interview/profile writing; email craft; nominalization/cohesion/flow; 'make this better'. SKIP: software/product/eng docs → technical-writing-craft; exec/business/persuasion → executive-comms; marketing/PR/newsletters → content-and-marketing-writing; career/academic/legal/policy/survey → career-and-formal-writing; AI-voice cleanup → kill-the-ai-ism; multi-pass doc critique → document-critique.",
}

results = []
for hub, newdesc in DESCS.items():
    p = os.path.join(SK, hub, "SKILL.md")
    if not os.path.exists(p):
        results.append((hub, "MISSING", 0)); continue
    txt = open(p, encoding="utf-8").read()
    m = re.match(r'^(---\s*\n)(.*?)(\n---\s*\n)(.*)$', txt, re.S)
    if not m:
        results.append((hub, "NO-FRONTMATTER", 0)); continue
    pre, fm, mid, body = m.groups()
    # remove existing description block (from 'description:' to next top-level key or end)
    fm2 = re.sub(r'(?ms)^description:.*?(?=^[A-Za-z_][\w-]*:\s|\Z)', '', fm)
    block = "description: >-\n" + "\n".join("  " + l for l in newdesc.split("\n")) + "\n"
    fm2 = block + fm2.lstrip("\n")
    newtxt = pre + fm2.rstrip("\n") + mid + body
    if len(newdesc) > CAP:
        results.append((hub, f"STILL-OVER({len(newdesc)})", len(newdesc))); continue
    if APPLY: open(p, "w", encoding="utf-8").write(newtxt)
    results.append((hub, "ok", len(newdesc)))

print(f"{'HUB':32} {'STATUS':16} CHARS")
for h, s, n in results:
    print(f"{h:32} {s:16} {n}")
over = [r for r in results if r[1] not in ("ok",)]
print(f"\n{'APPLIED' if APPLY else 'DRY-RUN'}: {sum(1 for r in results if r[1]=='ok')}/{len(results)} ok, {len(over)} issues")
